### ISSUE TITLE
Is this a bug?

### ISSUE THREAD

**Issue by aweiu** [maninak/ts-xor#18]
[Live Demo](https://www.typescriptlang.org/play/index.html#code/C4TwDgpgBA6glsAFgewK7ADwBUA0UCqAfFALxQDeUA2gApRwB2UAogB4DGANqgCYQYBrCCGQAzKLihCR4ogF0A-AC4oDCADcIAJygBfANwAoUJCgANAPIAlbHiKkoACixQAPgQCUUCK2AQGPADOUMgARgBWEOzAUApO8EhomJL2AGSebvEIKOgY+HhYxOlYXiou7vhGhsbg0BZgwHDITGTkDACGALYQKoHAWowA5rpQ6ZY25GDtSL39Q7p45OyIcJw8Wv4q9Y3NVHK6hNUA9EdQ7M19IQ1NDFvXzQ5tXT1QAOQAjK94UzNvryMnEICQyA84MS7Ie63KDbG6PDrdFQfL5nFZrDbQvYA07IYGgi4xSE7aGwh6tBEvZF4dTtbiUlHLVbrTbUfZQQHaLTILR4ULoIHVPhcdobM4Eq7Eu7E6pwcSOIk3AB0jPR-i8CuayrRzIYyua7Gmjg8hggnEC0A1up+iEVwGQABlkAbOBB8GBIFoAMLtc1GmVyy2K63qqFB6Y2u2O52u93ab2+42m80SpUqnV6hgG4BG9mnADuiBAsQAhIYgA)

**Comment by thatsnotnice** [comment]
i wouldn't call it so

it is due to the strictNullCheck flag
while ```Option``` is defined,  ```Array<Option>``` can still be undefined
(it has been an explicit choice to behave this way, it has to do with index signature performance and legacy compatibility if I remember, you can search about this matter online. there's something [here](https://github.com/Microsoft/TypeScript/pull/7140).


```if (option.children)``` on line 13 is both a type guard AND an explicit null check on ```children```
```if (option.path)``` on line 16 instead acts only as type guard, but doesn't check ```children```

in these cases i normally add a [fallback ](https://www.typescriptlang.org/play/index.html?target=99&ssl=15&ssc=1&pln=16&pc=1#code/C4TwDgpgBA6glsAFgewK7ADwBUA0UCqAfFALxQDeUA2gApRwB2UAogB4DGANqgCYQYBrCCGQAzKLihCR4ogF0A-AC4oDCADcIAJygBfANwAoUJCgANAPIAlbHiKkoACixQAPgQCUUCK2AQGPADOUMgARgBWEOzAUApO8EhomJL2AGSebvEIKOgY+HhYxOlYXiou7vhGhsbg0BZgwHDITGTkDACGALYQKoHAWowA5rpQ6ZY25GDtSL39Q7p45OyIcJw8Wv4q9Y3NVHK6hNUA9EdQ7M19IQ1NDFvXzQ5tXT1QAOQAjK94UzNvryMnEICQyA84MS7Ie63KDbG6PDrdFQfL5nFZrDbQvYA07IYGgi4xSE7aGwh6tBEvZF4dTtbiUlHLVbrTbUfZQQHaLTILR4ULoIHVPhcdobM4Eq7Eu7E6pwcSOIk3AB0jPR-i8VEVmoVzWVaOZDDkhggnEC0G1DEVP0QiuAyAAMsh2LSIPgwJAtABhdqmxweGVy82W6aILyBq02+2O52u91en1+42m6iaxWBlX6tzuPZyIxAA) on empty array

**Comment by aweiu** [comment]
@thatsnotnice 
[New Demo](https://www.typescriptlang.org/play/index.html#code/C4TwDgpgBA6glsAFgewK7ADwBUA0UCqAfFALxQDeUA2gApRwB2UAogB4DGANqgCYQYBrCCGQAzKLihCR4ogF0A-AC4oDCADcIAJygBfANwAoUJCgANAPIAlbHiKkoACixQAPgQCUUCK2AQGPADOUMgARgBWEOzAUApO8EhomJL2AGSebvEIKOgY+HhYxOlYXiou7vhGhsbg0BZgwHDITGTkDACGALYQKoHAWowA5rpQ6ZY25GDtSL39Q7p45OyIcJw8Wv4q9Y3NVHK6hNUA9EdQ7M19IQ1NDFvXzQ5tXT1QAOQAjK94UzNvryMnEICQyA84MS7Ie63KDbG6PDrdFQfL5nFZrDbQvYA07IYGgi4xSE7aGwh6tBEvZF4dTtbiUlHLVbrTbUfZQQHaLTILR4ULoIHVPhcdobM4Eq7Eu7E6pwcSOIk3AB0jPR-i8CuayrRzIYyua7Gmjg8hggnEC0A1up+iEVwGQABlkAbOBB8GBIFoAMLtc1GmVyy2K61QACEJDIqACEFEjAgPHVUKD0xtdsdztd7u03t9xtN5olSpVOr1DANwCN7NOCFewVx-qcgetCeJSaQtodTtpGY92YgfrzFsTRYxJbLFcBSEHLeDnXaIFC0FeKMCyG8Wi5WiAA)

**Comment by maninak** [comment]
@aweiu in the couple of times I sat to invest time looking into this issue, I haven't come up with an answer for you yet (sorry!).

But I saw you just closed the issue yourself, so if you've resolved the issue some how, I'd love it if you shared your findings with all of us. :)

**Comment by aweiu** [comment]
> @aweiu in the couple of times I sat to invest time looking into this issue, I haven't come up with an answer for you yet (sorry!).
> 
> But I saw you just closed the issue yourself, so if you've resolved the issue some how, I'd love it if you shared your findings with all of us. :)

https://github.com/maninak/ts-xor/issues/18#issuecomment-563059024, In this comment, I have described the cause of the problem：
![image](https://user-images.githubusercontent.com/15623620/100425572-733f7e00-30ca-11eb-89c0-d45731884fb2.png)

**Comment by maninak** [comment]
I understand. I'm aware of this line in the code you've shared above.

Perhaps I wasn't clear. My question was: why did you close the issue? If you think this issue is resolved I'd love it if you shared your thoughts (or even make an PR). If this problem is still not resolved, I'd prefer to have the issue remain open for visibility.

**Comment by aweiu** [comment]
Because this issue is caused by improper use of typescript type, not because of your library. So I close it.
