### ISSUE TITLE
Issue with function xor array

### ISSUE THREAD

**Issue by wawyed** [maninak/ts-xor#19]
For some reason comparing a function vs an array fails :(
[Playground Link](https://www.typescriptlang.org/play/index.html#code/KYDwDg9gTgLgBDAnmYcDqBLGALCBXGAHgBUAaOAVQD44BeOAbwCg44BtABTgwDs4BREAGMANngAmwQgGtgiCADM4ZOLPlLqAXRZwA-DoBccHsABuwKEwC+TJqEiwEyVAA0A8gCUS5anTgAKYjgAH0oASjhQGGAecQBnOAgAIwArYCEYHV0AzBx8IhVfADJwkJysXAJCCnJiGhLiMMNlMopbJiQUOABBKCgAQ0QXaAAxPB4MjAg+encvXoHEQn8I2ho4mCheAHMqchW6dc2dqgBuWwB6C+VsDAS4ypFxHgByeCTUBX6MER29JiE0w2cH6RgWg2GUDGExgUxmAVWNGYrFYUGAMDwUD4LwAzC9zjYAUD3mC+hDRuNJtM-GwDmtGDo0RisXBcfjrJpzh1nD0yYg3FDKbDqfRwUs6UctjxdmV-BK4BspdswlzATxgf0AIykxYC6FU+Hy5EopmY7F4gm2NXApLa3m6wUwuE0rWcoA)

**Comment by maninak** [comment]
Hey, thanks for filing an issue.

Could you please elaborate on what is the expected and actual behaviour? I'm having a hard time understanding what "comparing a function vs an array fails" means.

**Comment by wawyed** [comment]
Hi, sorry  the link didn't work. I've updated it and it should be more clear what the problem is. Let me know if you want me to clarify further.

**Comment by maninak** [comment]
Looks like a bug, possibly because in javascript

``` javascript
typeof [] // 'object'
```

#justJavascriptThings :man_facepalming: 

I'll investigate further in the upcoming days as soon as I get the time and hopefully.

**Comment by maninak** [comment]
There should never be a specific need to have exclusively a function or exclusively an array, since those are always mutually exclusive by default.

As a counter-example, try to assign _both_ a function _and_ an array to a variable (the way that your playground link shows). It's not something that is possible in JavaScript.

In such a use case the union operator (`|`) is what one should use.

Hence, I don't see this as a bug. If I'm missing something, please let me know.
