### ISSUE TITLE
Wrong built files mapping when using lastest ECMAScript Modules config in tsconfig.json

### ISSUE THREAD

**Issue by hoangngocthanh** [maninak/ts-xor#23]
Due to https://www.typescriptlang.org/docs/handbook/esm-node.html, it required a full import with file extension when using latest ECMAScript Modules config in tsconfig.json, so it cause a bug that can not expose the XOR declaration.
How to reproduce:
Set: compilerOptions.moduleResolution: "NodeNext" in tsconfig.json

![image](https://github.com/maninak/ts-xor/assets/43567759/0e7dd41d-65a0-4fd6-8e92-aba922ae6704)

**Comment by maninak** [comment]
Interesting. Thank you for reporting this!

A quick [audit with publint](https://publint.dev/ts-xor@1.1.0) shows no errors and one suggestion:

![image](https://github.com/maninak/ts-xor/assets/7542054/fb2ae164-1b5a-47f1-9185-671902620b4f)

I wonder if addressing that will fix it or if there's more to it. I definitely want to look more into this.

**Comment by maninak** [comment]
@hoangngocthanh could you please append the full contents of your `tsconfig.json` file in your original message?

**Comment by maninak** [comment]
Should be fixed with [v1.1.1](https://github.com/maninak/ts-xor/releases/tag/v1.1.1). @hoangngocthanh please let me know how that works for you.

Also, any feedback about the new release's compatibility with existing repos importing `ts-xor` and having different tsconfig configurations would also be appreciated. Tried my best not too, but it's hard to know I haven't introduced a regression with the cjs/esm mess... :man_shrugging:

**Comment by hoangngocthanh** [comment]
> Should be fixed with [v1.1.1](https://github.com/maninak/ts-xor/releases/tag/v1.1.1). @hoangngocthanh please let me know how that works for you.
> 
> Also, any feedback about the new release's compatibility with existing repos importing `ts-xor` and having different tsconfig configurations would also be appreciated. Tried my best not too, but it's hard to know I haven't introduced a regression with the cjs/esm mess... 🤷‍♂️

I find it working well with v1.1.1, thanks for the support!
